#!/bin/bash

mydir="$( cd "$(dirname "$0")" && /usr/bin/env pwd )"
export PATH="$mydir":"$PATH"

name="$1"
shift
port="$1"
shift

_ssh_nocheck $(_hagrid_user)@$(resolv:hagrid) docker port "$name" "$port" | _extract_port.sed
