#!/bin/bash

mydir="$( cd "$(dirname "$0")" && /usr/bin/env pwd )"
export PATH="$mydir":"$PATH"

ssh nikos@$(resolv:hagrid) docker rm -f ide_intelli
ssh nikos@$(resolv:hagrid) docker run --name ide_intelli -d -v /home/nikos/homes/ide:/home/nikos -ti -p 22 intelli
