#!/bin/bash

sockdir="$(dirname "$SSH_AUTH_SOCK")"
sock="$(basename "$SSH_AUTH_SOCK")"
docker run -e DISPLAY=$DISPLAY -e SSH_AUTH_SOCK=/ssh-agent/$sock -v /tmp/.X11-unix:/tmp/.X11-unix -v $sockdir:/ssh-agent "$@"
