#!/bin/bash

mydir="$(cd "$(dirname "$0")" && /usr/bin/env pwd)"
export PATH="$mydir":"$PATH"

if [[ $# < 1 ]]; then
  printf 'Usage:\n\n    %s REPO_NAME\n' "$0" 1>&2
  exit 1
fi

project_name="$1"
shift

address="$(_irma:get_repo_address "$project_name")"
git clone ssh://nikos@$(resolv:hagrid):$(irma:port)/"$address"
