#!/bin/bash

mydir="$(cd "$(dirname "$0")" && /usr/bin/env pwd)"
export PATH="$mydir":"$PATH"

address="$(_irma:get_repo_address)"
comm="$(_shellescape 'if [ ! -d '\'"$address"\'' ]; then git init --bare '\'"/$address"\''; fi' )"
irma:ssh bash -c "$comm"
