#!/bin/bash

mydir="$(cd "$(dirname "$0")" && /usr/bin/env pwd)"
export PATH="$mydir":"$PATH"

address="ssh://$(_hagrid_user)@$(resolv:hagrid):$(irma:port)/$(_irma:get_repo_address)"

if git remote | grep -E -e '^irma$'
then
  git remote set-url irma "$address"
else
  git remote add irma "$address"
fi

_ssh_enable irma
