#!/bin/bash

mydir="$( cd "$(dirname "$0")" && /usr/bin/env pwd )"

irma_start_command="$(_shellescape \
	'docker rm -f -v irma irma_home ; ' \
	'docker run --name irma_home -d -v /home/$(_hagrid_user) -ti intelli /bin/true ; ' \
	'docker run --name irma -d -v /home/$(_hagrid_user)/homes/irma:/irma --volumes-from irma_home -ti -p 22 intelli ; ' )"
_ssh_nocheck $(_hagrid_user)@$(resolv:hagrid) bash -x -c "$irma_start_command"
